// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://rcikbzgclqkandwabjny.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InJjaWtiemdjbHFrYW5kd2Fiam55Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NzIzNjYzMzEsImV4cCI6MjA4Nzk0MjMzMX0.uI13Ip7wunFd5vuvTy6IA9Lx_MhbtbIOnbYfx9CYtgw";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});